name = "wonderwall"
main = "./workers/app.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./build/client"

[vars]
VITE_CONVEX_URL = "https://courteous-rabbit-750.convex.cloud"
